on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Name of environment'
        required: true
      region:
        description: 'Location of resources'
        required: true
        default: 'westeurope'
      group:
        description: 'Terraform state group, not the actual Azure resource group.'
        required: true

jobs:
  azure-resources:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event.inputs.environment_name }}

    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'


      - name: create resource group        
        env:
          rg_name:  ${{ secrets.AZURE_ENVIRONMENT_GROUP }}-${{ github.event.inputs.environment_name }}-${{ github.event.inputs.group }}-tf
        run: |
          if [[ ! `az group exists --name ${{ env.rg_name }}` ]]; then 
            az group create --name ${{ env.rg_name }}-tf --location ${{ github.event.inputs.region }}
          fi

      


